version: "3"

services:
  party-games:
    container_name: party-games
    build:
      context: .
      dockerfile: ./apps/games/Dockerfile
    image:  ghoshanjega.azurecr.io/party-games
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  party-api:
    container_name: party-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    image:  ghoshanjega.azurecr.io/party-api
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true