export const C = {
  PLAYER_MAX_HP: 100,
  PLAYER_MIN_SPEED: 40,
  PLAYER_MAX_SPEED: 180,
  PLAYER_START_SIZE: 25,
  PLAYER_MAX_SIZE: 100,

  AGAR_START_COUNT: 100,
  AGAR_MIN_SIZE: 3,
  AGAR_MAX_SIZE: 9,

  BULLET_RADIUS: 3,
  BULLET_SPEED: 800,
  BULLET_DAMAGE: 10,

  SCORE_BULLET_HIT: 20,
  SCORE_PER_SECOND: 1,

  MAP_SIZE: 3000,
}
