name: Fly Deploy
on:
  push:
    branches:
      - develop
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup FLY
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy games
        run: flyctl deploy --remote-only --config fly.games.toml

      - name: Deploy api
        run: flyctl deploy --remote-only --config fly.api.toml
